FROM golang:1.8 as builder

ENV SRC=/go/src/github.com/infobloxopen/cni-infoblox

COPY . ${SRC}
WORKDIR ${SRC}

RUN go build -o bin/infoblox-plugin ./plugin


FROM alpine:3.5

ENV SRC=/go/src/github.com/infobloxopen/cni-infoblox
COPY --from=builder ${SRC}/bin/infoblox-plugin /install/bin/infoblox

RUN apk add --no-cache bash
RUN apk add --no-cache jq

ADD scripts/install-cni.sh /install/install-cni.sh
RUN chmod +x /install/bin/infoblox
RUN chmod +x /install/install-cni.sh

ARG GIT_SHA
ARG BUILD_DATE

LABEL GIT_SHA=$GIT_SHA \
      BUILD_DATE=$BUILD_DATE